import { Router } from "express";

import { validate } from "../../middlewares/validation.middleware.js";
import { authenticate } from "../auth/auth.middleware.js";
import { asyncHandler } from "../../utils/asyncHandler.js";
import { getMySettlementController } from "./settlement.controller.js";
import { sellerSettlementQuerySchema } from "./settlement.schema.js";

const router = Router();

router.use(authenticate);

/**
 * @openapi
 * /api/v1/sellers/settlement:
 *   get:
 *     tags:
 *       - Sellers
 *     summary: Get my settlement for a period
 *     description: Returns the authenticated seller's settlement for the given month (defaults to the current month). Returns null when no settlement exists for the period. Settlements are generated by an admin during the monthly payout window (1st-7th).
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - name: month
 *         in: query
 *         required: false
 *         description: Month in YYYY-MM format (e.g. 2026-07)
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Settlement fetched (or null when none exists)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   $ref: "#/components/schemas/Settlement"
 *                   nullable: true
 *       400:
 *         description: Invalid month format
 *       401:
 *         description: Not authenticated
 */
router.get(
  "/settlement",
  validate(
    sellerSettlementQuerySchema,
    "query",
  ),
  asyncHandler(getMySettlementController),
);

export default router;
